### PR TITLE
cpp: export functions to transform isl [pw_] aff to sets

### PR DESCRIPTION
**Pull request by tobiasgrosser**

### CODE REVIEW

**Comment by tobiasgrosser** [comment]
@ftynse , @nicolasvasilache : You wanna do a quick code-review to check how code-reviews work for us. Once passed, I will submit this to Sven.

**Review by ftynse — APPROVED** [review]
LGTM

**Comment by nicolasvasilache** [comment]
Looks good!

**Comment by tobiasgrosser** [comment]
Submitted to Sven.

**Comment by tobiasgrosser** [comment]
These have been upstreamed to isl.

**Comment by tobiasgrosser** [comment]
Actually, this has not yet been merged.

**Comment by tobiasgrosser** [comment]
Merged into isl.

**Pull request closed without merging**
